### PR TITLE
tree_entry: fix CommitsInfo messed up with entries have the same SHA1

### PR DESCRIPTION
**Pull request by manfer**
to fix https://github.com/gogs/gogs/issues/6186
to fix https://github.com/gogs/gogs/issues/6235
to fix https://github.com/gogs/gogs/issues/6240

The problem is on git-module

https://github.com/gogs/git-module/blob/cf0a6d71b880c42c4dd507b59be762c5a05c649a/tree_entry.go#L261-L270

An entry id is not unique so it should not be used as map key. When on a tree there is a file or folder with same contents its SHA1 hash is equal. This can be tested in any repo with two files with same content executing `git ls-tree HEAD`

```cmd
$ mkdir testrepo; cd testrepo
$ git init
$ echo "this is a test" > test1
$ git add .
$ git commit -m "adding test1 file"
$ echo "this is a test" > test2
$ git add .
$ git commit -m "adding test2 file"
$ git ls-tree HEAD
100644 blob 90bfcb510602aa11ae53a42dcec18ea39fbd8cec    test1
100644 blob 90bfcb510602aa11ae53a42dcec18ea39fbd8cec    test2
```

Maybe a solution is using name as the key as I bet entry name is unique in any tree.

```go
	infos := make(map[string]*EntryCommitInfo, len(es))
	for info := range results {
		infos[info.Entry.name] = info
	}


	commitsInfo := make([]*EntryCommitInfo, len(es))
	for i, e := range es {
		commitsInfo[i] = infos[e.name]
	}
	return commitsInfo, nil
```

Or maybe just including entry index on info so later only one loop is needed to fill commitsInfo.

```go

// EntryCommitInfo contains a tree entry with its commit information.
type EntryCommitInfo struct {
	Entry     *TreeEntry
        Index     int
	Commit    *Commit
	Submodule *Submodule
}

        ...
			go func(e *TreeEntry, i int) {
				defer func() {
					wg.Done()
        ...

				info := &EntryCommitInfo{
					Entry: e,
                                        Index: i,
				}

        ...

				results <- info
			}(e, i)
		}
	}()

        ...

	commitsInfo := make([]*EntryCommitInfo, len(es))
	for info := range results {
		commitsInfo[info.Index] = info
	}
	return commitsInfo, nil
```

### CODE REVIEW

**Comment by unknwon** [comment]
@manfer: Wow, thanks a lot for the great details! LGTM at first glance, I'll take a deeper look later this week.

**Review by unknwon — APPROVED** [review]

**Comment by unknwon** [comment]
I'm merging it as-is, then add a test case later.

**Comment by unknwon** [comment]
https://github.com/gogs/git-module/releases/tag/v1.1.2 has tagged for this merge.

**Comment by xZero707** [comment]
@manfer Amazing work. Thank you!

**Pull request merged**
